on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Build the Docker image
            #run: docker build . --file Dockerfile
          run: docker compose up --build

        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: workspace_artifacts
            path: ${{ github.workspace }}